[package]
name = "try-rust"
version = "0.1.0"
authors = ["Andrei Oprisan <aoprisan@gmail.com>"]

[dependencies.rustless]
git = "https://github.com/rustless/rustless"

[dependencies]
nix = "0.5.0"
rustc-serialize = "0.3.19"
hyper = "0.8.1"
iron = "0.3.0"
valico = "0.8.2"
